spring:
  kafka:
    consumer:
      value-deserializer: "org.springframework.kafka.support.serializer.JsonDeserializer"
      properties:
        "[spring.json.value.default.type]": "edu.miu.sa.reservation.entity.Order"
        "[spring.json.trusted.packages]": "edu.miu.sa.reservation"
    producer:
      value-serializer: "org.springframework.kafka.support.serializer.JsonSerializer"
      properties:
        "[spring.json.add.type.headers]": false

---
spring:
  config:
    activate:
      on-profile: dev
  kafka:
    bootstrap-servers: "localhost:9092"
kafka:
  topic: "ReservationOrderEvent"

---
spring:
  config:
    activate:
      on-profile: prod
  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVERS}
kafka:
  topic: ${RESERVATION_ORDER_EVENT}