spring:
  kafka:
    consumer:
      value-deserializer: "org.springframework.kafka.support.serializer.JsonDeserializer"
      properties:
        "[spring.json.value.default.type]": "edu.miu.sa.reservation.entity.Reservation"
        "[spring.json.trusted.packages]": "edu.miu.sa.reservation"
    producer:
      value-serializer: "org.springframework.kafka.support.serializer.JsonSerializer"
      properties:
        "[spring.json.add.type.headers]": false

---
spring:
  config:
    activate:
      on-profile: dev
  kafka:
    bootstrap-servers: "localhost:9092"

  main:
    allow-bean-definition-overriding: true

  data:
    cassandra:
      contact-points: "localhost"
      port: 9042
      keyspace-name: reservation
      schema-action: create_if_not_exists
      local-datacenter: datacenter1

kafka:
  topic:
    payment: "PaymentRequestEvent"
    property: "ReservationDoneEvent"
    notification: "GetNotificationEvent"

jwt:
  secret: "top_secret"
---
spring:
  config:
    activate:
      on-profile: prod
  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVERS}

  main:
    allow-bean-definition-overriding: ${ALLOW_BEAN_DEFINITION_OVERRIDING}
  data:
    cassandra:
      contact-points: ${CASSANDRA_CONTACT_POINTS}
      port: ${CASSANDRA_PORT}
      keyspace-name: ${CASSANDRA_KEYSPACE}
      schema-action: ${CASSANDRA_SCHEME_ACTION}
      local-datacenter: ${CASSANDRA_DATACENTER}
kafka:
  topic:
    payment: ${PAYMENT_TOPIC}
    property: ${RESERVATION_TOPIC}
    notification: ${NOTIFICATION_TOPIC}

jwt:
  secret: ${JWT_SECRET}